sudo: false

language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database cra_travis_ci_express_test;' -U postgres
  - psql -c "CREATE USER postgres_test WITH PASSWORD null;" -U postgres
  - npm run build
  - npm install -g sequelize-cli
  - sequelize db:migrate
script:
  - npm test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: client/build
  on:
    branch: master

after_success:
  - npm run coverage